ROCm enable sparse_sampled_addmm
ROCmSoftwarePlatform/pytorch pull request #1126
Opened 2022-10-11 16:13 UTC by jpvillam-amd

Enables:
test_comprehensive_sparse_sampled_addmm_cuda_complex128
test_comprehensive_sparse_sampled_addmm_cuda_complex64
test_comprehensive_sparse_sampled_addmm_cuda_float32
test_comprehensive_sparse_sampled_addmm_cuda_float64
test_dispatch_meta_sparse_sampled_addmm_cuda_complex128
test_dispatch_meta_sparse_sampled_addmm_cuda_complex64
test_dispatch_meta_sparse_sampled_addmm_cuda_float32
test_dispatch_meta_sparse_sampled_addmm_cuda_float64
test_meta_sparse_sampled_addmm_cuda_complex128
test_meta_sparse_sampled_addmm_cuda_complex64
test_meta_sparse_sampled_addmm_cuda_float32
test_meta_sparse_sampled_addmm_cuda_float64

2022-10-11 18:14 UTC, pruthvistony approved these changes
The changes are fine.
Waiting for CI run to check if above tests are executed successfully.

2022-10-12 06:18 UTC, pruthvistony commented
Oct 11 19:57:04   test_comprehensive_sparse_sampled_addmm_cuda_complex128 (__main__.TestDecompCUDA) ... ok (0.164s)
Oct 11 19:57:04   test_comprehensive_sparse_sampled_addmm_cuda_complex64 (__main__.TestDecompCUDA) ... ok (0.071s)
Oct 11 19:57:04   test_comprehensive_sparse_sampled_addmm_cuda_float32 (__main__.TestDecompCUDA) ... ok (0.054s)
Oct 11 19:57:04   test_comprehensive_sparse_sampled_addmm_cuda_float64 (__main__.TestDecompCUDA) ... ok (0.056s)

Oct 11 20:33:09   test_dispatch_meta_sparse_sampled_addmm_cuda_complex128 (__main__.TestMetaCUDA) ... ok (0.026s)
Oct 11 20:33:09   test_dispatch_meta_sparse_sampled_addmm_cuda_complex64 (__main__.TestMetaCUDA) ... ok (0.008s)
Oct 11 20:33:09   test_dispatch_meta_sparse_sampled_addmm_cuda_float32 (__main__.TestMetaCUDA) ... ok (0.008s)
Oct 11 20:33:09   test_dispatch_meta_sparse_sampled_addmm_cuda_float64 (__main__.TestMetaCUDA) ... ok (0.007s)

Oct 11 20:37:11   test_meta_sparse_sampled_addmm_cuda_complex128 (__main__.TestMetaCUDA) ... ok (0.008s)
Oct 11 20:37:11   test_meta_sparse_sampled_addmm_cuda_complex64 (__main__.TestMetaCUDA) ... ok (0.008s)
Oct 11 20:37:11   test_meta_sparse_sampled_addmm_cuda_float32 (__main__.TestMetaCUDA) ... ok (0.008s)
Oct 11 20:37:11   test_meta_sparse_sampled_addmm_cuda_float64 (__main__.TestMetaCUDA) ... ok (0.007s)

2022-10-12 06:23 UTC, pruthvistony requested changes

2022-10-12 06:23 UTC, pruthvistony commented on torch/testing/_internal/common_cuda.py
> +def _get_torch_hip_version():
NIT comment - better to name this function `_get_torch_rocm_version`

2022-10-13 15:34 UTC, jpvillam-amd commented
Not really sure why the CI failed here. Could anyone help me figure it out?

2022-10-14 02:36 UTC, pruthvistony commented
jenkins retest this please

2022-10-14 02:41 UTC, pruthvistony commented
jenkins retest this please

2022-10-14 02:42 UTC, pruthvistony commented
> Not really sure why the CI failed here. Could anyone help me figure it out?

I also didnt get why it was failing, then realized it is due to git merge conflict. Resolved it.

2022-10-14 22:15 UTC, pruthvistony commented
The tests are passing
Oct 14 04:35:18   test_comprehensive_sparse_sampled_addmm_cuda_complex128 (__main__.TestDecompCUDA) ... ok (0.146s)
Oct 14 04:35:18   test_comprehensive_sparse_sampled_addmm_cuda_complex64 (__main__.TestDecompCUDA) ... ok (0.063s)
Oct 14 04:35:18   test_comprehensive_sparse_sampled_addmm_cuda_float32 (__main__.TestDecompCUDA) ... ok (0.052s)
Oct 14 04:35:18   test_comprehensive_sparse_sampled_addmm_cuda_float64 (__main__.TestDecompCUDA) ... ok (0.051s)

2022-10-14 22:15 UTC, pruthvistony approved these changes

2022-10-14 22:15 UTC, merged