call filelock function
ROCmSoftwarePlatform/pytorch pull request #1191
Opened 2023-02-24 08:39 UTC by pramenku

call install_filelock before install_triton

To fix https://ontrack-internal.amd.com/browse/SWDEV-384803

Fixes #ISSUE_NUMBER

2023-02-24 10:01 UTC, pruthvistony requested changes
Was hesitant to do this change, may be ok for 5.5 but 5.6 needs to be reverted after the IFU.
since it is NOT proper way.

2023-02-25 16:18 UTC, pramenku commented on .jenkins/pytorch/test.sh
> +  install_filelock
Removed L928

2023-02-25 16:20 UTC, pramenku commented
> Was hesitant to do this change, may be ok for 5.5 but 5.6 needs to be reverted after the IFU.
Sure, @pruthvistony  we can revert after IFU merge for 5.6. Till that time, at least we will able to test those module and report any new bug.

2023-02-28 12:32 UTC, pramenku commented
Hi @pruthvistony can you please merge it today in 5.5 n 5.6.

We couldn't test these modules in automation until this PR is merged.

Thanks

2023-02-28 23:18 UTC, pruthvistony approved these changes

2023-02-28 23:18 UTC, merged