Fix circular recursion issue in hipification
ROCmSoftwarePlatform/pytorch pull request #1244
Opened 2023-06-15 05:27 UTC by lcskrishna

This PR fixes the circular issue during the hipification process by using Iterative DFS instead of DFS with the introduction of current_state. Also, a new class HipifyResult has been introduced which holds hipified_path, status and current_state for each individual source file instead of a dict.

2023-06-15 16:57 UTC, jithunnair-amd requested changes
Looks good, needs minor changes

2023-06-15 16:57 UTC, jithunnair-amd commented on torch/utils/hipify/hipify_python.py
> +            hipify_result.current_state = "done"
Let's replace these strings with an enum or equivalent.

2023-06-15 16:57 UTC, jithunnair-amd commented on torch/utils/hipify/hipify_python.py
>                  hipified_header_filepath = HIPIFY_FINAL_RESULT[header_filepath]["hipified_path"]
We can probably remove these

2023-06-15 16:57 UTC, jithunnair-amd commented on torch/utils/hipify/hipify_python.py
> +    hipify_result = HIPIFY_FINAL_RESULT[fin_path]
Please add a comment that this is to get the updated value of `HIPIFY_FINAL_RESULT[fin_path]`

2023-06-15 17:09 UTC, jithunnair-amd commented
Let's mention some details of the flash_attention hipification issue that you resolved using this PR

2023-06-19 09:30 UTC, lcskrishna commented on torch/utils/hipify/hipify_python.py
> +            hipify_result.current_state = "done"
Done.

2023-06-19 09:52 UTC, lcskrishna commented
> Let's mention some details of the flash_attention hipification issue that you resolved using this PR

The circular issue arises when we try to hipify flash-attention_private include dirs from these two files which import each other.
```
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/710e20819c9065c58610d4ad11a0eea2c19db91e/include/ck/utility/multi_index.hpp
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/710e20819c9065c58610d4ad11a0eea2c19db91e/include/ck/utility/common_header.hpp
```

The following error is seen:
```
File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 822, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 812, in repl
    preprocess_file_and_save_result(output_directory,
  File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 177, in preprocess_file_and_save_result
    result = preprocessor(output_directory, filepath, all_files, header_include_dirs, stats,
  File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 822, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 812, in repl
    preprocess_file_and_save_result(output_directory,
  File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 177, in preprocess_file_and_save_result
    result = preprocessor(output_directory, filepath, all_files, header_include_dirs, stats,
  File "/opt/conda/lib/python3.8/site-packages/hipify_torch/hipify_python.py", line 733, in preprocessor
    rel_filepath = os.path.relpath(filepath, output_directory)
  File "/opt/conda/lib/python3.8/posixpath.py", line 471, in relpath
    start_list = [x for x in abspath(start).split(sep) if x]
  File "/opt/conda/lib/python3.8/posixpath.py", line 375, in abspath
    if not isabs(path):
  File "/opt/conda/lib/python3.8/posixpath.py", line 63, in isabs
    sep = _get_sep(s)
  File "/opt/conda/lib/python3.8/posixpath.py", line 42, in _get_sep
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

This PR fixes the recursion issue and hipifies successfully.

2023-06-22 19:45 UTC, merged

2023-06-22 20:08 UTC, jithunnair-amd commented
@lcskrishna Let's file an upstream PR for this

2023-06-23 03:11 UTC, lcskrishna commented
Created an upstream PR: https://github.com/pytorch/pytorch/pull/104085