Workaround of SWDEV-407984
ROCmSoftwarePlatform/pytorch pull request #1254
Opened 2023-07-10 18:28 UTC by xinyazhang

Also Fixes #SWDEV-406932

2023-07-10 18:33 UTC, xinyazhang commented
Tested locally on Navi 32. No regressions.
```
(py_3.8) xinyazha@f18cdb1110e2:~/rocm-pytorch/test$ sh ~/t_geqrf.sh
[W Module.cpp:1349] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
/home/xinyazha/rocm-pytorch/torch/_functorch/deprecated.py:65: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.grad is deprecated as of PyTorch 2.0 and will be deleted in a future vers
ion of PyTorch >= 2.3. Please use torch.func.grad instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('grad')
.../home/xinyazha/rocm-pytorch/torch/testing/_internal/opinfo/core.py:1097: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:2426.)
  return self.op(*args, **kwargs)
....../home/xinyazha/rocm-pytorch/torch/_functorch/deprecated.py:73: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vjp is deprecated as of PyTorch 2.0 and will be deleted in a future
 version of PyTorch >= 2.3. Please use torch.func.vjp instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vjp')
............../home/xinyazha/rocm-pytorch/torch/_functorch/deprecated.py:61: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vmap is deprecated as of PyTorch 2.0 and will be deleted in
 a future version of PyTorch >= 2.3. Please use torch.vmap instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vmap', 'torch.vmap')
..../home/xinyazha/rocm-pytorch/torch/autograd/__init__.py:319: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::ormqr. Please file us an issue on GitHub so that we can prioritize it
s implementation. (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/home/xinyazha/rocm-pytorch/torch/autograd/__init__.py:319: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::tril_. Please file us an issue on GitHub so that we can prioritize its im
plementation. (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
................./home/xinyazha/rocm-pytorch/torch/testing/_internal/opinfo/core.py:1097: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::ormqr. Please file us an issue on GitHub so
 that we can prioritize its implementation. (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  return self.op(*args, **kwargs)
....
----------------------------------------------------------------------
Ran 48 tests in 244.121s

OK
/home/xinyazha/rocm-pytorch/torch/_functorch/deprecated.py:61: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vmap is deprecated as of PyTorch 2.0 and will be deleted in a future vers
ion of PyTorch >= 2.3. Please use torch.vmap instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vmap', 'torch.vmap')
../home/xinyazha/rocm-pytorch/test/functorch/common_utils.py:32: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:2426.)
  out = op(*pytree.tree_unflatten(new_args, args_spec), **kwarg_values)
.[W Module.cpp:1349] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
../home/xinyazha/rocm-pytorch/torch/testing/_internal/opinfo/core.py:1097: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::ormqr. Please file us an issue on GitHub so that we can pr
ioritize its implementation. (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  return self.op(*args, **kwargs)
/home/xinyazha/rocm-pytorch/torch/_functorch/vmap.py:621: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::ormqr. Please file us an issue on GitHub so that we can prioritize its impl
ementation. (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  batched_outputs = func(*batched_inputs, **kwargs)
/home/xinyazha/rocm-pytorch/test/functorch/common_utils.py:266: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::ormqr. Please file us an issue on GitHub so that we can prioritize it
s implementation. (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  return op(*args, **kwargs)
..
----------------------------------------------------------------------
Ran 7 tests in 6.299s

OK
..............
----------------------------------------------------------------------
Ran 14 tests in 97.597s

OK
......test_linalg.py:3537: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:2426.)
  Q, R = torch.qr(A, some=some)
test_linalg.py:3555: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at /home/xinyazha/rocm-pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:2438.)
  torch.qr(A, some=some, out=(Q_out, R_out))
....
----------------------------------------------------------------------
Ran 10 tests in 5.419s

OK
.............
----------------------------------------------------------------------
Ran 13 tests in 52.167s

OK
.......[W Module.cpp:1349] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
............................................
----------------------------------------------------------------------
Ran 51 tests in 367.304s

OK
...[W Module.cpp:1349] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
./home/xinyazha/rocm-pytorch/torch/testing/_internal/opinfo/core.py:769: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mod [...]

2023-07-12 19:39 UTC, pruthvistony requested changes
hipblasLT integration revert is already done. - https://github.com/ROCmSoftwarePlatform/pytorch/pull/1253
So this PR needs to include only changes related to - SWDEV-407984

2023-07-12 19:40 UTC, pruthvistony commented on aten/src/ATen/cuda/CUDABlas.cpp
> +#if !defined(USE_ROCM)
ignore this comment since it is part of the hipblasLT revert.

2023-07-12 21:19 UTC, jithunnair-amd commented
> hipblasLT integration revert is already done. - https://github.com/ROCmSoftwarePlatform/pytorch/pull/1253
So this PR needs to include only changes related to - SWDEV-406932

@xinyazhang Please rebase this PR branch so it reflects only the changes relevant to geqrf issue

2023-07-12 21:30 UTC, xinyazhang commented on aten/src/ATen/cuda/CUDABlas.cpp
> +#if ROCM_VERSION == 50700
This patch is a workaround and the proper solution is being tracked in SWDEV-407984.
I though the problem will be eventually fixed in ROCM 5.8 or maybe 5.7 so I'm setting == 50700.
(Maybe >= 57000 and < 50800 is a better condition?)

2023-07-12 21:43 UTC, jithunnair-amd commented on aten/src/ATen/cuda/CUDABlas.cpp
> +#if ROCM_VERSION == 50700
Yes, I prefer >= 50700 and < 50800

2023-07-13 17:10 UTC, xinyazhang commented
@jithunnair-amd @pruthvistony Done. All geqrf related local tests passed

2023-07-13 17:11 UTC, jithunnair-amd approved these changes

2023-07-13 17:11 UTC, merged

2023-07-13 17:41 UTC, pruthvistony reviewed
LGTM