Added decorator `skipRocmIfTorchInductor`
ROCmSoftwarePlatform/pytorch pull request #1306
Opened 2023-10-25 18:51 UTC by pragupta

Fixes #ISSUE_NUMBER

2023-10-30 06:24 UTC, pruthvistony requested changes

2023-10-30 06:24 UTC, pruthvistony commented on test/test_torch.py
> +    TEST_WITH_CROSSREF, skipIfTorchDynamo, skipRocmIfTorchInductor,
Why is set_default_dtype removed?

2023-10-30 16:20 UTC, pragupta commented on test/test_torch.py
> +    TEST_WITH_CROSSREF, skipIfTorchDynamo, skipRocmIfTorchInductor,
Sorry, bad merge

2023-10-31 13:36 UTC, jataylo approved these changes
LGTM but could we link the upstream PR in the description @pragupta

2023-10-31 15:52 UTC, pragupta commented
> LGTM but could we link the upstream PR in the description @pragupta

Updated PR description.

2023-10-31 16:12 UTC, pruthvistony approved these changes

2023-10-31 16:12 UTC, merged