Hipsparselt Integration for Rocm6.3
ROCmSoftwarePlatform/pytorch pull request #1602
Opened 2024-09-26 19:54 UTC by petrex

Cherry-pick from https://github.com/pytorch/pytorch/pull/133934/

With hipsparselt && hipblaslt fixes after mainline 14782 :   112 UT expected passing, 7 UT will be skip due to hipsparselt support.

2024-09-26 20:05 UTC, rocm-mici commented
Jenkins build for [611e3322f8fe4ab6d254c0f90eaa5f7c1e88f3fa](https://github.com/ROCm/pytorch/commit/611e3322f8fe4ab6d254c0f90eaa5f7c1e88f3fa) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/1/artifact)

2024-09-26 22:08 UTC, rocm-mici commented
Jenkins build for [7e63cb25749d6e0761c875020b1cd6a8d8ee9a30](https://github.com/ROCm/pytorch/commit/7e63cb25749d6e0761c875020b1cd6a8d8ee9a30) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/2/artifact)

2024-09-26 22:28 UTC, rocm-mici commented
Jenkins build for [7e63cb25749d6e0761c875020b1cd6a8d8ee9a30](https://github.com/ROCm/pytorch/commit/7e63cb25749d6e0761c875020b1cd6a8d8ee9a30) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/3/artifact)

2024-09-26 22:28 UTC, rocm-mici commented
Jenkins build for [7e63cb25749d6e0761c875020b1cd6a8d8ee9a30](https://github.com/ROCm/pytorch/commit/7e63cb25749d6e0761c875020b1cd6a8d8ee9a30) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/4//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/4/artifact)

2024-09-26 22:52 UTC, rocm-mici commented
Jenkins build for [7e63cb25749d6e0761c875020b1cd6a8d8ee9a30](https://github.com/ROCm/pytorch/commit/7e63cb25749d6e0761c875020b1cd6a8d8ee9a30) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/5//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/5/artifact)

2024-09-27 03:59 UTC, rocm-mici commented
Jenkins build for [5603ad59f9fea68d8ee17b467fc0fed2186103a4](https://github.com/ROCm/pytorch/commit/5603ad59f9fea68d8ee17b467fc0fed2186103a4) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/6//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/6/artifact)

2024-10-01 18:31 UTC, rocm-mici commented
Jenkins build for [5603ad59f9fea68d8ee17b467fc0fed2186103a4](https://github.com/ROCm/pytorch/commit/5603ad59f9fea68d8ee17b467fc0fed2186103a4) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/7//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/7/artifact)

2024-10-03 22:20 UTC, petrex commented
Sync with upstream https://github.com/pytorch/pytorch/pull/133934/

2024-10-03 22:43 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/9//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/9/artifact)

2024-10-03 22:44 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/8//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/8/artifact)

2024-10-04 17:07 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/10//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/10/artifact)

2024-10-04 18:07 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/12//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/12/artifact)

2024-10-07 16:53 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/13//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/13/artifact)

2024-10-08 05:02 UTC, pruthvistony requested changes

2024-10-08 05:02 UTC, pruthvistony commented on aten/src/ATen/native/sparse/cuda/SparseSemiStructuredOps.cu
> +__global__ void reorder_meta_kernel(Element* dest, const Element* src,
Are these functions required? Dont see them called from ROCm code.

2024-10-08 05:40 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/14//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/14/artifact)

2024-10-09 07:22 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/15//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/15/artifact)

2024-10-09 07:22 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/16//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/16/artifact)

2024-10-10 06:22 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/17//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/17/artifact)

2024-10-10 20:14 UTC, rocm-mici commented
Jenkins build for [36f5443fb3e69889138d07d87fcc6b33b44eef28](https://github.com/ROCm/pytorch/commit/36f5443fb3e69889138d07d87fcc6b33b44eef28) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/19//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/19/artifact)

2024-10-10 20:55 UTC, petrex commented
@pruthvistony CI fails at 
`0
20:13:49  + wget --no-check-certificate -q -O - https://hub.docker.com/v2/namespaces/rocm/repositories/pytorch/tags?page_size=50
1
script returned exit code 4`

any tips?

2024-10-10 21:26 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/20//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/20/artifact)

2024-10-14 18:56 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/21//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/21/artifact)

2024-10-18 06:53 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/22//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/22/artifact)

2024-10-22 22:00 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/23//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/23/artifact)

2024-10-23 07:53 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/24//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/24/artifact)

2024-10-24 09:02 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/25//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/25/artifact)

2024-10-25 23:18 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/26//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/26/artifact)

2024-10-28 18:05 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/27//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/27/artifact)

2024-10-30 19:00 UTC, rocm-mici commented
Jenkins build for [d8e7986f2412e9f7c8042f799a30b2ffaffb1f87](https://github.com/ROCm/pytorch/commit/d8e7986f2412e9f7c8042f799a30b2ffaffb1f87) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/28//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/28/artifact)

2024-11-01 01:03 UTC, rocm-mici commented
Jenkins build for [0310b9fd7a133a64397d02f0e8172dd9640368c9](https://github.com/ROCm/pytorch/commit/0310b9fd7a133a64397d02f0e8172dd9640368c9) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/29//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/29/artifact)

2024-11-04 22:05 UTC, rocm-mici commented
Jenkins build for [c4b1db35f0d54e9debf14d912cae375a9d938090](https://github.com/ROCm/pytorch/commit/c4b1db35f0d54e9debf14d912cae375a9d938090) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/30//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/30/artifact)

2024-11-05 21:09 UTC, rocm-mici commented
Jenkins build for [c4b1db35f0d54e9debf14d912cae375a9d938090](https://github.com/ROCm/pytorch/commit/c4b1db35f0d54e9debf14d912cae375a9d938090) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/31//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/31/artifact)

2024-11-12 18:34 UTC, rocm-mici commented
Jenkins build for [336121897d03bc966e2f256c0a5274e451c96f2c](https://github.com/ROCm/pytorch/commit/336121897d03bc966e2f256c0a5274e451c96f2c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/34//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/34/artifact)

Detected error during base docker image building: 
```
#29 15.91 The following packages have unmet dependencies:
#29 15.98  rocm-dev : Depends: rocm-cmake (= 0.13.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 15.98             Depends: rocm-device-libs (= 1.0.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 15.98  rocm-utils : Depends: rocminfo (= 1.0.0.60203-124~22.04)
#29 15.98               Depends: rocm-cmake (= 0.13.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 15.99 E: Unable to correct problems, you have held broken packages.
#29 ERROR: process "/bin/sh -c bash ./install_rocm.sh" did not complete successfully: exit code: 100
------
 > [24/49] RUN bash ./install_rocm.sh:
15.91 distribution that some required packages have not yet been created
15.91 or been moved out of Incoming.
```

2024-11-13 19:33 UTC, rocm-mici commented
Jenkins build for [336121897d03bc966e2f256c0a5274e451c96f2c](https://github.com/ROCm/pytorch/commit/336121897d03bc966e2f256c0a5274e451c96f2c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/35//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/35/artifact)

Detected error during base docker image building: 
```
#29 18.93 The following packages have unmet dependencies:
#29 18.98  rocm-dev : Depends: rocm-cmake (= 0.13.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 18.98             Depends: rocm-device-libs (= 1.0.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 18.98  rocm-utils : Depends: rocminfo (= 1.0.0.60203-124~22.04)
#29 18.98               Depends: rocm-cmake (= 0.13.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 18.99 E: Unable to correct problems, you have held broken packages.
#29 ERROR: process "/bin/sh -c bash ./install_rocm.sh" did not complete successfully: exit code: 100
------
 > [24/49] RUN bash ./install_rocm.sh:
18.93 distribution that some required packages have not yet been created
18.93 or been moved out of Incoming.
```

2024-11-21 17:53 UTC, okakarpa commented
Jenkins build for [336121897d03bc966e2f256c0a5274e451c96f2c](https://github.com/ROCm/pytorch/commit/336121897d03bc966e2f256c0a5274e451c96f2c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/36//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/36/artifact)

Detected error during base docker image building: 
```
#29 12.55 The following packages have unmet dependencies:
#29 12.61  rocm-dev : Depends: rocm-cmake (= 0.13.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 12.61             Depends: rocm-device-libs (= 1.0.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 12.61  rocm-utils : Depends: rocminfo (= 1.0.0.60203-124~22.04)
#29 12.61               Depends: rocm-cmake (= 0.13.0.60203-124~22.04) but 5.0.0-1 is to be installed
#29 12.62 E: Unable to correct problems, you have held broken packages.
#29 ERROR: process "/bin/sh -c bash ./install_rocm.sh" did not complete successfully: exit code: 100
------
 > [24/49] RUN bash ./install_rocm.sh:
12.55 distribution that some required packages have not yet been created
12.55 or been moved out of Incoming.
```

2024-12-04 05:45 UTC, rocm-mici commented
Jenkins build for [336121897d03bc966e2f256c0a5274e451c96f2c](https://github.com/ROCm/pytorch/commit/336121897d03bc966e2f256c0a5274e451c96f2c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1602/38//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1602/38/artifact)

2025-10-19 04:01 UTC, closed without merging